version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./app/public:/var/www/html/public # ★ここを修正しました！
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - wordpress
    networks:
      - app-network

  php:
    build: ./php
    volumes:
      - ./app:/var/www/html # これはNginxとは別のパス（PHPアプリケーションのルート）なのでこのままでOK
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  # WordPress サービス
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: tiper
      WORDPRESS_DB_USER: tiper
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  wordpress_data: