version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html # プロジェクトルート全体をコンテナの /var/www/html にマウント
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - blog_wordpress_service
    networks:
      - app-network

  php:
    build: ./php
    volumes:
      - .:/var/www/html
    # ホストのユーザーIDとグループIDでPHPプロセスを実行
    # .env ファイルに CURRENT_UID と CURRENT_GID を設定してください
    user: "${CURRENT_UID}:${CURRENT_GID}" 
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: tiper
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASSWORD}
      DUGA_API_KEY: ${DUGA_API_KEY}
      TZ: Asia/Tokyo
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: my_web_project-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: tiper
      MYSQL_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: tiper
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/database:/db_scripts
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  blog_wordpress_service:
    image: wordpress:latest
    container_name: wordpress_blog_container
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: tiper
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      TZ: Asia/Tokyo
    volumes:
      - ./wordpress_blog:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
