services:
  nginx:
    build: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443" # HTTPSポートも公開
    volumes:
      - .:/var/www/html # プロジェクトルート全体をコンテナの /var/www/html にマウント
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro # ★追加: Certbot証明書を読み取り専用でマウント
    depends_on:
      - php
      - mysql
      - phpmyadmin
      - blog_wordpress_service
    networks:
      - app-network

  php:
    build: ./php
    volumes:
      - .:/var/www/html
      # ホストのユーザーIDとグループIDでPHPプロセスを実行
      - ./logs:/var/www/html/logs
      # .env ファイルに CURRENT_UID と CURRENT_GID を設定してください
      - ./php.ini:/usr/local/etc/php/php.ini # ★この行に修正！★
      #- ./php.ini:/usr/local/etc/php/php.ini # ★この行を修正します！
    # ホストのユーザーIDとグループIDでPHPプロセスを実行
    user: "${CURRENT_UID}:${CURRENT_GID}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: tiper
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASSWORD} # アプリケーションコードでどちらを参照しているか確認し、不要ならDB_PASSWORDを残して削除しても良い
      DUGA_API_KEY: ${DUGA_API_KEY}
      DUGA_API_URL: ${DUGA_API_URL}
      ADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD} # ★ここを追加しました
      TZ: Asia/Tokyo
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: my_web_project-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # ここを修正します。WordPressが期待するDB名、ユーザー、パスワードを直接指定します。
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}      # .envのWORDPRESS_DB_NAMEを参照
      MYSQL_USER: ${WORDPRESS_DB_USER}          # .envのWORDPRESS_DB_USERを参照
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}  # .envのWORDPRESS_DB_PASSWORDを参照
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/database:/db_scripts
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  blog_wordpress_service:
    image: wordpress:latest
    container_name: wordpress_blog_container
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: tiper
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DEBUG: 1
      TZ: Asia/Tokyo
    volumes:
      - ./wordpress_blog:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: